# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KooraLive' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KooraLive
  pod 'Alamofire'
  pod 'RealmSwift'
  pod 'Kingfisher'

  target 'KooraLiveTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KooraLiveUITests' do
    # Pods for testing
  end

end
